### ISSUE TITLE
Add `to_path_normalized`

### ISSUE THREAD

**Issue by matklad** [udoprog/relative-path#3]
I have a `../foo` `RelativePathBuf` and a `/bar` `std::PathBuf`. I'd like to be able to get `/foo` out of it, **without** calling `Path::canonicalize` (which is a failable syscall). Perhaps adding a `to_path_normalized` with this semantics would work?

**Comment by udoprog** [comment]
Mentoring notes:

This would require implementing a version of [`relative_traversal`](https://github.com/udoprog/relative-path/blob/master/src/lib.rs#L173) that works with a mix of [`path::Component`](https://doc.rust-lang.org/std/path/enum.Component.html) and `relative_path::Component` over a `PathBuf` instance.

Anyone who is interested in normalization might also want to go and shout in rust-lang/rust#47402 since that would supersede the need to do it in this crate.

**Comment by udoprog** [comment]
I think we already support this with [`RelativePath::normalize`](https://docs.rs/relative-path/latest/relative_path/struct.RelativePath.html#method.normalize) now.
