### ISSUE TITLE
serde::Deserialize trait on RelativePathBuf permits absolute paths

### ISSUE THREAD

**Issue by jwodder** [udoprog/relative-path#41]
Despite the fact that `RelativePathBuf` is supposed to reject any absolute paths, the following program:

```rust
use relative_path::RelativePathBuf;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Foo {
    path: RelativePathBuf
}

fn main() {
    let p = serde_json::from_str::<Foo>(r#"{"path": "/foo.txt"}"#);
    match p {
        Err(_) => println!("Task failed successfully"),
        Ok(v) => println!("Expected error, got {v:?}"),
    }
}
```

outputs:

```
Expected error, got Foo { path: "/foo.txt" }
```

**Comment by udoprog** [comment]
Yeah, a relative path can be freely constructed through any underlying string, the only restriction is when converting from a `Path` or `PathBuf` object.

This is because there is no portable way to determine if a string is absolute or not that works on *every* platform, we just feed it the string and treat it using the rules of the wrapper type. The rule here would cause any leading slashes to be ignored when treating it as components:

```rust
use relative_path::{Component, RelativePath};

assert!(RelativePath::new("/foo/bar").components().eq([Component::Normal("foo"), Component::Normal("bar")]));
assert_eq!(RelativePath::new("/foo/bar"), "foo/bar");
assert_eq!(RelativePath::new("foo/bar"), "foo/bar");
```
