### ISSUE TITLE
Relax dependencies requirements

### ISSUE THREAD

**Issue by Sytten** [udoprog/relative-path#56]
Unless you explicitly need something from `serde` `1.0.160`, it is generally a best practice for a lib to limit it's dependencies to major and minor versions.

**Comment by udoprog** [comment]
It's very hard to know when something was introduced or a buggy behavior fixed in `serde`, and since it has such a relaxed MSRV the latest version should be pretty much universally usable. So I just tend to record the latest version I use when I built something using it as a requirement.

Unfortunately I don't really have the tooling nor the time to find the least supported version.

Is there a particular issue you're running into?

**Comment by Sytten** [comment]
Fair, I had to upgrade some versions in our projects. I still feel this is not your responsibility to check every patch either. The version requirement from my perspective should only be on the API offered but other positions are defendable.
In general strict dependency versions are annoying because they increase the likelihood of versioning conflict with other deps (not really the case here but still).
Do feel free to close, thanks for the reply :)
